version: "3.9"

services:
  app:
    build:
      dockerfile: ./Dockerfile
    command:
      - gunicorn
      - mysite_19.wsgi:application
      - --bind
      - 0.0.0.0:8000
    ports:
      - "8000:8000"
    
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200k"
    volumes:
      - ./mysite_19/database:/app/database

  nginx:
    build:
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  database:
