# Generated by Django 4.2.1 on 2023-10-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogapp", "0003_alter_article_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="pub_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(to="blogapp.tag"),
        ),
    ]
