# Generated by Django 4.2.1 on 2023-07-17 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0004_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopapp.order'),
        ),
    ]
