# Generated by Django 4.2.1 on 2023-08-29 02:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shopapp", "0005_productimage_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name": "Order", "verbose_name_plural": "Orders"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name", "price"],
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
    ]
