# Generated by Django 4.2.1 on 2023-09-01 01:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shopapp", "0006_alter_order_options_alter_product_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
