# Generated by Django 4.2.1 on 2023-09-11 00:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shopapp", "0007_alter_product_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                db_index=True, decimal_places=2, default=0, max_digits=9
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="quantity",
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
    ]
